'use strict';
// ============================================================================
//  Trainers of Solmere. party: [{sp, lvl, moves?, item?, nature?, abil?}]
// ============================================================================
(function () {
  const T = (id, cls, name, look, party, lines = {}, o = {}) => { G.TRAINERS[id] = { cls, name, look, party: party.map(([sp, lvl, extra]) => ({ sp, lvl, ...(extra || {}) })), money: o.money || 30, ai: o.ai !== undefined ? o.ai : 2, ...lines, ...o }; };
  const gymO = (o = {}) => ({ money: 45, ai: 2, env: 'gym', ...o });
  const leader = (o) => ({ money: 120, ai: 3, boss: true, music: 'gym_battle', victory: 'victory_gym', noRematch: true, env: 'gym', ...o });
  const grunt = (o = {}) => ({ money: 40, ai: 2, music: 'villain_battle', encounterMusic: 'encounter_villain', noRematch: true, ...o });
  const admin = (o = {}) => ({ money: 90, ai: 3, boss: true, music: 'admin_battle', encounterMusic: 'encounter_villain', noRematch: true, ...o });
  const elite = (o = {}) => ({ money: 150, ai: 4, boss: true, music: 'elite', victory: 'victory_gym', noRematch: true, env: 'league', resonate: true, ...o });

  // ------------------------------------------------------------ ROUTE 1
  T('r1_kid', 'Kid', 'Timmy', 'kid', [['nibbit', 3]], { intro: 'My Nibbit can chew through anything! Want to see?', defeat: 'Aww. My Nibbit tried its best.', after: 'Nibbit\'s teeth never stop growing, so it chews on sticks all day.' });
  T('r1_lass', 'Lass', 'Poppy', 'lass', [['pipwing', 3], ['mossbun', 4]], { intro: 'Is that your first Echo? Mine too! Let\'s battle!', defeat: 'You\'re good! Were you really just starting out?', after: 'My Pipwing keeps diving at the reeds on the far side of the pond. There must be something shiny in there.' });
  T('r1_bug', 'Bug Maniac', 'Pip', 'bugmaniac', [['grubbit', 6], ['grubbit', 7]], { intro: 'Shh! You\'ll scare the bugs! ...Oh, you want to battle? Even better!', defeat: 'My Grubbits! They were so brave.', after: 'Grubbit are slow now, but wait until they evolve. Everything is worth a second look.' });
  T('r1_boy', 'Youngster', 'Ned', 'boy', [['nibbit', 6], ['pipwing', 7]], { intro: 'I\'ve been training up here all week. You don\'t stand a chance!', defeat: 'All week... for this?', after: 'I went to Juniper with just my Nibbit. She was very kind about it, and I lost anyway.' });
  // ------------------------------------------------------- FERNWICK GYM
  T('fg_1', 'Gardener', 'Rosa', 'farmer', [['mossbun', 9], ['shroomie', 10]], { intro: 'Every flower in this gym was planted by hand. Mind where you step!', defeat: 'My petals... wilted.', after: 'The Warden\'s garden takes before it gives. Watch what her first Echo does before it ever attacks.' }, gymO());
  T('fg_2', 'Gardener', 'Tobin', 'farmer', [['shroomie', 10], ['mossbun', 10]], { intro: 'Warden Juniper is the kindest person in Fernwick. And the toughest!', defeat: 'You\'re the real thing.', after: 'Leech Seed drains a little health every turn. It adds up fast!' }, gymO());
  // Juniper has a plan, not levels: Shroomie opens with Stun Spore and Leech Seed and drains from behind them,
  // and Fawnbloom carries Mud Shot for the Fire starter everyone brings (the Emberjay flies over it).
  // Measured by tests/attention.js: a team that just walked the road wins about half the time, one that
  // listened (Route 1's Tamers, the Emberjay at its roost) wins comfortably, one that skipped everything loses.
  T('juniper', 'Warden', 'Juniper', 'juniper', [['mossbun', 9, { moves: ['vinewhip', 'quickstrike', 'tailwhip', 'absorb'] }], ['shroomie', 9, { moves: ['stunspore', 'leechseed', 'megadrain', 'poisonsting'] }], ['fawnbloom', 11, { item: 'oranberry', moves: ['vinewhip', 'charmleaf', 'mudshot', 'growl'] }]],
    { intro: '', defeat: 'Oh my. You and your partners bloom together beautifully.', retry: 'You came back. Good. Did you watch what my garden did before it ever struck? ...Then show me.' }, leader({ items: { superpotion: 1 } }));
  // ------------------------------------------------------------ ROUTE 2
  T('r2_bug', 'Bug Maniac', 'Wes', 'bugmaniac', [['grubbit', 7], ['grubbit', 7], ['cocoonet', 8]], { intro: 'Behold my army of future Aurorymoths!', defeat: 'My army still has some growing to do.', after: 'Grubbit evolves quickly: at level 7, then again at 10.' });
  T('r2_hiker', 'Hiker', 'Dale', 'hiker', [['pebblin', 9], ['pebblin', 10]], { intro: 'HAH! Rocks! Nothing is as steady as a good rock!', defeat: 'I\'ve been ground down!', after: 'I keep an Ether buried up above the ledge, north of here, in case a climb runs long. Don\'t tell anyone.' });
  T('r2_lass', 'Lass', 'Juno', 'lass', [['glimmer', 9], ['pipwing', 10]], { intro: 'My Glimmer glows when it\'s happy! Let\'s make it glow!', defeat: 'It\'s still glowing... but now it\'s glowing at you!', after: 'Glimmer evolves when it truly trusts you. No stone needed.' });
  T('r2_twins', 'Twins', 'Ami & Mei', 'twins', [['nibbit', 9], ['mossbun', 9]], { intro: 'We\'re twins, and we battle together! Two against two!', defeat: 'We lost... together!', after: 'In double battles, some moves hit both foes at once.' }, { double: true, money: 25 });
  T('r2_kid', 'Kid', 'Leo', 'boy', [['stingle', 8], ['nibbit', 9]], { intro: 'Stingle\'s stinger is tiny, but it hurts!', defeat: 'Owww. Okay, you win.', after: 'My sister hid her Skill Disc against the trees, south of where the road turns east, and now she can\'t find it. Don\'t tell her if you do.' });
  // --------------------------------------------------------- WHISPERWOOD
  T('ww_bug', 'Bug Maniac', 'Kit', 'bugmaniac', [['beetlet', 11], ['stingle', 11]], { intro: 'Whisperwood is the best forest in Solmere for finding bugs!', defeat: 'Squashed...', after: 'The Beetlet in the clearing to the north-east leave silver dust on everything they touch. I\'ve never found where it all comes from.' });
  T('ww_ranger', 'Ranger', 'Ivy', 'ranger', [['mossbun', 11], ['glimmer', 12]], { intro: 'Rangers protect these woods. Show me you respect them!', defeat: 'You\'re kind to your Echoes. I can tell. They keep looking back at you.', after: 'The grey coats went toward the shrine. Please hurry.' });
  T('ww_mystic', 'Mystic', 'Wendel', 'mystic', [['wispurr', 12], ['oddowl', 12]], { intro: 'The trees have been whispering about a visitor... and here you are.', defeat: 'The whispers were right about you.', after: 'Not everything lying in these woods is what it seems. And the trees whisper of something sweet, buried where the trail bends for the last time before Galvan.' });
  T('ww_grunt1', 'Hollow Grunt', 'Grunt', 'grunt', [['nibbit', 11], ['blotch', 12]], { intro: 'This is Hollow business! Turn around!', defeat: 'Tch! The Director won\'t be pleased.', after: 'We\'re only following orders.' }, grunt());
  T('ww_grunt2', 'Hollow Grunt', 'Grunt', 'grunt_f', [['rascoon', 12], ['blotch', 13]], { intro: 'You beat my partner? Then you\'ll have to beat me too!', defeat: 'Fine! We already have a shard anyway!', after: '...' }, grunt());
  // --------------------------------------------------------------- GALVAN
  T('gv_sailor', 'Sailor', 'Brody', 'sailor', [['clawdle', 15], ['flopfin', 14]], { intro: 'Ahoy! A battle to warm the blood on a cold sea day!', defeat: 'Sunk me like an anchor!', after: 'Old Salt Marv swears a Flopfin becomes something magnificent. I\'m starting to believe him.' });
  T('gv_worker', 'Worker', 'Mack', 'worker', [['gearling', 16], ['pebblin', 15]], { intro: 'It\'s my break. Let\'s battle!', defeat: 'Back to work, I suppose.', after: 'I dropped a Magnet off the gym roof last spring. It went over the east side, down by the water. Never did find it.' });
  T('gg_1', 'Punk', 'Zed', 'punk', [['voltpup', 14], ['zipsquee', 14]], { intro: 'The Galvan Gym runs on lightning! And so do I!', defeat: 'Short-circuited!', after: 'Ione always opens with her Zipsquee. It hangs in the air, where nothing on the ground can reach it.' }, gymO());
  T('gg_2', 'Punk', 'Roxy', 'punk', [['gearling', 15], ['voltpup', 15]], { intro: 'Found the right switches? You still have to get past me!', defeat: 'Out of power!', after: 'Step on the glowing pads to lower the barriers.' }, gymO());
  T('gg_3', 'Engineer', 'Faye', 'scientist', [['gearling', 15], ['jellume', 16]], { intro: 'I wired this gym myself. I know every trick in it!', defeat: 'I didn\'t plan for that.', after: 'Ione\'s Jellume drinks lightning. I\'ve watched challengers pour every spark they had into it and just make it stronger.' }, gymO());
  // Ione has a plan too: Zipsquee leads, floating over any Ground Echo sent against it, and paralyses whatever is
  // fastest; Voltpup bites; Jellume drinks Electric moves (Volt Sponge) and answers Ground with Water Gun. Her gym
  // Tamers say each of these out loud. tests/attention.js measures it as it does Juniper.
  T('ione', 'Warden', 'Ione', 'ione', [['zipsquee', 14, { moves: ['staticwave', 'aerialace', 'spark', 'quickstrike'] }], ['voltpup', 15, { moves: ['joltnuzzle', 'bite', 'spark', 'quickstrike'] }], ['jellume', 17, { item: 'oranberry', moves: ['watergun', 'zap', 'confusion', 'growl'] }]],
    { intro: '', defeat: 'Well done! You outpaced the current!', retry: 'Back again! Did you listen to my Tamers this time, or just run faster? ...Let\'s find out.' }, leader({ items: { superpotion: 1 } }));
  // --------------------------------------------------------------- ROUTE 3
  T('r3_swim1', 'Swimmer', 'Kai', 'swimmer', [['clawdle', 16], ['lillipad', 16]], { intro: 'The water\'s perfect! So is my team!', defeat: 'Glub glub...', after: 'Someday you\'ll be able to surf. The Mere is huge!' });
  T('r3_swim2', 'Swimmer', 'Nia', 'swimmer_f', [['jellume', 17]], { intro: 'Jellume! Light them up!', defeat: 'Dimmed...', after: 'On summer nights, wild Jellume light up the whole harbour.' });
  // Bo stands off the road with his back to it (sight 0): only a player who walks over and talks gets his story,
  // which is the one pointer to Brann's plan (the sun) and to the Rain Call Disc behind the little trees
  T('r3_fisher', 'Fisher', 'Bo', 'fisher', [['flopfin', 12], ['flopfin', 14], ['flopfin', 16]], { intro: 'I only fish for the best. Behold, my Flopfin!', defeat: 'I\'ll keep believing in it!', after: 'I took my Flopfin to Brann\'s forge once. His lava slug turned the place into an oven, and my poor fish could barely splash. The old storm-callers on these cliffs brought the rain with a Skill Disc. One lost it in the thicket behind the little trees, by the cave. Nobody\'s bothered to cut through.' });
  T('r3_hiker', 'Hiker', 'Gus', 'hiker', [['digmole', 17], ['pebblin', 17]], { intro: 'These cliffs are my home ground!', defeat: 'An avalanche of defeat!', after: 'My friend Rocco went into Glimmer Cave three days ago and never came out. The Hollow has been in there, hauling crates.' });
  T('r3_ace', 'Ace Tamer', 'Lyra', 'ace_f', [['gustling', 18], ['lillipad', 18], ['voltpup', 18]], { intro: 'Ace Tamers train with purpose. Show me yours!', defeat: 'Your purpose is very clear.', after: 'Give your Echoes items to hold. A Sun Berry has saved me more than once.' }, { money: 50, ai: 3 });
  T('r3_kid', 'Kid', 'Pip', 'kid', [['pipwing', 15], ['gustling', 17]], { intro: 'Bird Echoes rule the sky, and this route!', defeat: 'Grounded!', after: 'Birds hate caves. Mine won\'t go near Glimmer. It says the walls sing at it.' });
  // --------------------------------------------------------- GLIMMER CAVE
  T('gc_hiker', 'Hiker', 'Dale', 'hiker', [['pebblin', 18], ['pebblin', 19]], { intro: 'Crystals and trainers! My two favourite things!', defeat: 'Crushed like quartz!', after: 'Halfway down the long passage, the Hollow dug a side tunnel out to a little pool. I watched one of them drop a Skill Disc in there and not even look back. Rocks falling from the sky, it said on the label.' });
  T('gc_grunt1', 'Hollow Grunt', 'Grunt', 'grunt', [['duskbat', 18], ['blotch', 19]], { intro: 'These crystals belong to Crane Dynamics now!', defeat: 'Aw, no.', after: 'The crystals store Resonance. That\'s what the scientists say.' }, grunt());
  T('gc_grunt2', 'Hollow Grunt', 'Grunt', 'grunt_f', [['rascoon', 19], ['gearling', 19]], { intro: 'Admin Lark said nobody gets past!', defeat: 'Lark is going to be furious with me.', after: '...She won\'t be, though. Lark never yells when we lose. She just goes quiet, like she expected it. That\'s worse.' }, grunt());
  T('gc_sci', 'Hollow Scientist', 'Dr. Pell', 'scientist', [['gearling', 19], ['magmite', 19]], { intro: 'Your Echo\'s Resonance readings are remarkable! Hold still!', defeat: 'The readings... they\'re off the charts!', after: 'Resonance is energy, and energy can be gathered. That is all we are doing.' }, grunt());
  T('lark1', 'Hollow Admin', 'Lark', 'lark', [['duskbat', 21], ['stingle', 22], ['rascoon', 23, { item: 'oranberry' }]], { intro: '', defeat: 'Tch! Fine! Keep your glowing rocks!' }, admin({ items: { potion: 1 } }));
  // ----------------------------------------------------------- CINDERVALE
  // Brann's gym Tamers each fight with one piece of his plan, then say it out loud once beaten (as Ione's do)
  T('cg_1', 'Smith', 'Hal', 'worker', [['magmite', 21, { abil: 2, moves: ['sunshine', 'ember', 'rockthrow'] }], ['emberjay', 21]], { intro: 'Welcome to the Forge! Mind the lava!', defeat: 'Quenched!', after: 'Felt that heat? The Warden lights the forge before anyone lands a real blow. Everything wet turns to steam for a while. A while, mind. Not forever.' }, gymO());
  T('cg_2', 'Smith', 'Ada', 'artist', [['magmite', 21], ['emberjay', 22]], { intro: 'Brann taught me to temper steel, and spirit!', defeat: 'My spirit needs more tempering.', after: 'Brann keeps his best for last, and it burns brightest while the forge is still hot. It drinks the light, too, and spits it back out as something no fire Echo should have. If the fire\'s gone out by then, it\'s just a big dog. A big dog with lightning in its teeth, mind.' }, gymO());
  T('cg_3', 'Blackbelt', 'Jo', 'blackbelt', [['scrapmonk', 22, { moves: ['lowsweep', 'rapidjab', 'braceup', 'chop'] }]], { intro: 'HYAH! Feel the fire in my fists!', defeat: 'I have been... extinguished.', after: 'The Warden\'s first Echo has never gone down to a single blow. Not once, in twenty years. Everyone who hits it thinks they almost had it.' }, gymO());
  // Brann's plan: his Magmite (Sturdy, so no single blow drops it) lights the forge with Sunshine, which halves Water;
  // his Emberjay (Sunchaser) is twice as fast in the sun; Emberail Resonates last, and while the sun still burns
  // its Solar Beam fires at once and Thunder Fang waits for the Water Echo everyone brings. It all hangs on the sun: a player who
  // runs the sun down before the ace arrives, or brings rain (the Disc Fisher Bo points to), wins; one who just brings
  // Water and charges in doesn't. Emberail can't relight it (hand play: with Sunshine and Charcoal it one-shot even
  // Echoes that resist fire, so nothing a player did mattered). tests/attention.js measures it.
  T('brann', 'Warden', 'Brann', 'brann', [['magmite', 21, { abil: 2, moves: ['sunshine', 'ember', 'rockthrow', 'braceup'] }], ['emberjay', 22, { abil: 2, moves: ['flamerush', 'wingslash', 'wispflame', 'quickstrike'] }], ['emberail', 23, { item: 'sunberry', moves: ['flamerush', 'firefang', 'solarbeam', 'thunderfang'] }]],
    { intro: '', defeat: 'HAAA! There\'s real fire in you!', retry: 'BACK AGAIN! Good! Steel that breaks once and comes back is the only kind worth having. Let\'s go!' }, leader({ resonate: true }));   // no potions: the one he'd carry went to the Sturdy Magmite at 1 HP and won the fight for Water Echoes (tests/attention.js)
  // --------------------------------------------------------------- ROUTE 4
  T('r4_hiker', 'Hiker', 'Ben', 'hiker', [['bouldrok', 25], ['digmole', 24]], { intro: 'Ash in my beard, and rocks in my heart!', defeat: 'Buried!', after: 'The hot springs in Cindervale will soothe your whole team.' });
  T('r4_ace', 'Ace Tamer', 'Rin', 'ace', [['emberjay', 25], ['lillipad', 25], ['zipsquee', 25]], { intro: 'A balanced team is a winning team!', defeat: 'I need more balance.', after: 'Balance means an answer for everything. Ghosts laugh at a Normal punch, you know. Funny thing: a Normal Echo laughs right back at theirs.' }, { money: 50, ai: 3 });
  T('r4_punk', 'Punk', 'Vic', 'punk', [['rascoon', 24], ['stingle', 24], ['waspear', 25]], { intro: 'Nobody walks this road without a battle.', defeat: 'All right. Go on through.', after: 'My Rascoon grew up under the Ruins stair. Nothing spooky ever got a trick past it, not once. Find your own in the gold grass, if you can catch one.' });
  T('r4_bb', 'Blackbelt', 'Taro', 'blackbelt', [['scrapmonk', 25], ['thornhare', 26]], { intro: 'I train on this ash road every morning!', defeat: 'My training is incomplete!', after: 'I tried Thornhare\'s kicks on a Wispurr once. They went straight through it. Kicks are no good in Duskmere.' });
  T('r4_mystic', 'Mystic', 'Luz', 'mystic', [['maskling', 25, { moves: ['hypnosis', 'hex', 'confusion', 'astonish'] }], ['wispurr', 25]], { intro: 'The spirits of Duskmere drift this far... and they speak of you.', defeat: 'The spirits approve of you.', after: 'Did your Echo nod off? That is how we fight in Duskmere. We learned it from the Warden. The lamplighter says she learned it from the dark.' });
  // ---------------------------------------------------------------- RUINS
  T('ru_grunt1', 'Hollow Grunt', 'Grunt', 'grunt', [['gnawmaw', 26], ['blotch', 26]], { intro: 'The Tide Key is ours! Turn back!', defeat: 'Admin Grey is going to be disappointed.', after: 'Admin Grey\'s Gearling hits you and it\'s gone before you can hit it back. Its lightning goes through anything with wings. Not through dirt, mind. Nothing goes through dirt.' }, grunt());
  T('ru_grunt2', 'Hollow Grunt', 'Grunt', 'grunt_f', [['duskbat', 26], ['rascoon', 27]], { intro: 'You again?! Everyone in the Hollow knows your face!', defeat: 'How are you this strong?!', after: 'Grey\'s Sludgor poisons you first. Then it really gets going. Grey says poison is "a multiplier". I don\'t know what that means, but it hurts.' }, grunt());
  T('ru_grunt3', 'Hollow Grunt', 'Grunt', 'grunt', [['gearling', 27], ['sludgor', 28]], { intro: 'This is the last line of defence! For the Director!', defeat: 'Line... breached...', after: 'A kid in a Fellowship scarf got here before any of us. Grey let them carry the key out. A kid! I\'ve been in the Hollow six years.' }, grunt());
  // Grey's plan: Gearling hits and pivots out with Volt Dash (nothing on the ground feels it), Sludgor poisons and then
  // Venom Shock doubles on the poison, Armadrill walls. His grunts each give away one piece (ru_grunt1-3). Hand play at
  // L31-34 with a Super Potion and Acid Armor: a team that walked the road lost every time, so tests/attention.js grey1
  // measures him (straight about 37%, prepared 99%); no potion, so a player's plan isn't undone by a heal.
  T('grey1', 'Hollow Admin', 'Grey', 'grey', [['gearling', 29], ['sludgor', 29, { moves: ['toxic', 'venomshock', 'sludge', 'bite'] }], ['armadrill', 30, { item: 'sunberry' }]], { intro: '', defeat: 'Interesting. You are statistically improbable.', retry: 'Again. Each attempt updates the model. Yours too, I hope.' }, admin());
  // ------------------------------------------------------------ DUSK GYM
  // Mireille's gym Tamers each fight with one piece of her plan, then say it once beaten (as Ione's and Brann's do)
  T('dg_1', 'Mystic', 'Rue', 'mystic', [['wispurr', 28, { abil: 2, moves: ['confuseray', 'hex', 'shadowsneak', 'bite'] }], ['maskling', 28]], { intro: 'Boo.', defeat: 'That was... supposed to scare you.', after: 'The Warden\'s little ones never strike first. They play a trick first, quicker than you can move. Only something born in the dark sees through a trick like that.' }, gymO());
  T('dg_2', 'Mystic', 'Sol', 'mystic', [['duskbat', 28], ['maskling', 29, { moves: ['hypnosis', 'hex', 'psybeam', 'nightshade'] }]], { intro: 'In darkness, only the brave see clearly.', defeat: 'You are brave indeed.', after: 'Hex is a whisper to a healthy Echo. To one that is asleep, or burning, or muddled, it is a scream. Keep yours awake.' }, gymO());
  T('dg_3', 'Mystic', 'Cass', 'mystic', [['coffret', 29]], { intro: 'Did you think I was a treasure chest? Hehehe...', defeat: 'Snap!', after: 'The Warden\'s last Echo sits and thinks. Every turn you give it to think, it gets harder to reach. Don\'t give it the time.' }, gymO());
  // Mireille's plan: her Echoes never strike a healthy one. Wispurr (Prankster) muddles yours before it can move, Maskling
  // puts it to sleep, and Hex hits twice as hard on anything with a status; Masquerail thinks (Calm Mind) and Resonates last.
  // A player who listened wins: a Dark Echo shrugs off Prankster tricks (Vic's Rascoon, the kid's Duskbats), a Normal Echo
  // can't be touched by Hex (Rin), Awakenings or a Chesto Berry undo the sleep (Luz, Sol), and hitting the ace before it
  // thinks too long (Cass). One who just charges in with Fighting or Normal moves hits nothing. tests/attention.js measures it.
  T('mireille', 'Warden', 'Mireille', 'mireille', [['wispurr', 30, { abil: 2, moves: ['confuseray', 'wispflame', 'hex', 'shadowsneak'] }], ['maskling', 31, { moves: ['hypnosis', 'hex', 'psybeam', 'nightshade'] }], ['phantomane', 32, { moves: ['hex', 'crunch', 'wispflame', 'shadowclaw'] }], ['masquerail', 33, { item: 'spelltag', moves: ['calmmind', 'hex', 'shadowball', 'psybeam'] }]],
    { intro: '', defeat: 'The candle flickers... and still it burns. As do you.', retry: 'You came back through the dark. Good. Did you listen to it this time?' }, leader({ resonate: true }));
  // --------------------------------------------------------------- ROUTE 5
  T('r5_swim1', 'Swimmer', 'Tess', 'swimmer_f', [['lillipad', 28], ['jellume', 29]], { intro: 'You can surf? Then you can battle!', defeat: 'Washed out!', after: 'There\'s a girl on the big islet to the east who found something in the reeds that glows. She won\'t stop talking about it. She says it sings.' });
  T('r5_swim2', 'Swimmer', 'Rob', 'swimmer', [['mireel', 29], ['clawdle', 28]], { intro: 'I\'ll race you to the next islet, right after this battle!', defeat: 'You\'d win the race too, I bet.', after: 'Mireel\'s ability ignores the foe\'s stat boosts.' });
  T('r5_swim3', 'Swimmer', 'Coral', 'swimmer_f', [['crustank', 30]], { intro: 'My Crustank is a fortress with legs!', defeat: 'The walls came down.', after: 'Rock on the outside, cold water on the inside. Up in Frostpeak a Blizzard just rolls off a Crustank. The Warden up there has never once beaten mine.' });
  T('r5_fisher', 'Fisher', 'Nell', 'fisher', [['flopfin', 25], ['riptalon', 30]], { intro: 'Everyone laughs at Flopfin. Nobody laughs at this!', defeat: 'Well... you can laugh now.', after: 'Patience is the secret. Patience, and Flopfin.' });
  T('r5_couple', 'Couple', 'Jan & Lee', 'lady', [['lillipad', 29], ['mireel', 29]], { intro: 'We do everything together, even battling!', defeat: 'At least we lost together.', after: 'In double battles, you need a plan for both of your Echoes.' }, { double: true, money: 35 });
  T('r5_ace', 'Ace Tamer', 'Dom', 'ace', [['tidetail', 31], ['gustling', 30], ['lillipad', 30]], { intro: 'I\'ve been waiting on this islet for a worthy opponent!', defeat: 'You were worth the wait!', after: 'Shiftail can evolve in many different ways. I chose Water.' }, { money: 50, ai: 3 });
  // ------------------------------------------------------------ FROSTPEAK
  T('fp_skier1', 'Skier', 'Kris', 'skier', [['snowlet', 32, { abil: 2 }], ['pengrost', 32, { moves: ['iceshard', 'icefang', 'rapidjab', 'wingslash'] }]], { intro: 'Fresh snow, and a fresh challenger!', defeat: 'Wiped out!', after: 'Did you see my Pengrost go? When the snow\'s falling, a Pengrost is twice as quick as anything on the mountain. Stop the snow and it\'s just a penguin again.' });
  T('fp_skier2', 'Skier', 'Anya', 'skier', [['icicub', 33, { moves: ['icefang', 'slash', 'bulldoze', 'iceshard'] }], ['pengrost', 33]], { intro: 'Race you down the mountain! Well, battle first!', defeat: 'You\'re fast!', after: 'A boy with an Emberjay tried to roast my Icicub last week. It just sat in the flames and yawned. Bears up here are all fur and fat. They hate the ground shaking, though.' });
  // Sigrid's gym Tamers each fight with one piece of her plan, then say it once beaten (as Mireille's do)
  T('ig_1', 'Skier', 'Bjorn', 'skier', [['snowlet', 33, { abil: 2, item: 'gritsash', moves: ['auroraveil', 'icygust', 'charmvoice', 'moonlight'] }], ['icicub', 34]], { intro: 'Did you slide to the right spot? You still have to beat me!', defeat: 'I\'m on thin ice.', after: 'The Warden\'s lead brings the snow down, and while it snows she hangs the aurora over her whole team. Hitting through that is like punching a wall. There\'s a Wall Breaker disc for that, you know. Somebody dropped one in the snow right outside this gym. Half the challengers walk straight past it.' }, gymO());
  T('ig_2', 'Skier', 'Lin', 'skier', [['pengrost', 34, { moves: ['iceshard', 'icefang', 'rapidjab', 'drainpunch'] }], ['snowlet', 34, { abil: 2, moves: ['snowfall', 'icygust', 'charmvoice', 'moonlight'] }]], { intro: 'Sigrid is waiting at the summit!', defeat: 'Avalanche!', after: 'Her last Echo sings a Blizzard that never misses while it snows. Stop the snow and it just calls it back down. So stop it again.' }, gymO());
  // Sigrid's plan: the snow is her armour. Aurorelle (Frostcall) brings the snow as it enters and hangs Aurora Veil, which
  // only holds in snow; in snow her Ice Echoes are harder to hit physically, Frostemper (Slush Rush) is twice as fast,
  // Glaciursa (Thick Fat) shrugs off the Fire everyone brings to an ice gym, and Frosttail's Blizzard never misses and
  // Snowfall calls the snow back. A player who listened takes the snow away (Halvard's rain: Rain Call, sold in the
  // specialty shop and found on Route 3), shatters the veil (Wall Breaker, lying in the snow by the gym door), or shakes
  // the ground under the bear (Anya). One who brings Fire and punches hits a wall. tests/attention.js measures it.
  T('sigrid', 'Warden', 'Sigrid', 'sigrid', [['aurorelle', 34, { abil: 2, moves: ['auroraveil', 'auroraray', 'moonlight', 'charmvoice'] }], ['frostemper', 34, { moves: ['icicledrop', 'drainpunch', 'iceshard', 'braceup'] }], ['glaciursa', 35, { moves: ['icicledrop', 'earthquake', 'slash', 'icefang'] }], ['frosttail', 37, { item: 'nevermeltice', moves: ['blizzard', 'frostbreath', 'snowfall', 'auroraray'] }]],
    { intro: '', defeat: 'Incredible! Like the first clear morning after a blizzard!', retry: 'Back up the mountain! Good. Nobody climbs a peak on the first try. Did you look at the sky this time?' }, leader({ resonate: true }));
  // ----------------------------------------------------------- MT. GLACIA
  T('mg_hiker', 'Hiker', 'Olaf', 'hiker', [['bouldrok', 34], ['armadrill', 35]], { intro: 'Brr! A battle will warm us up!', defeat: 'Still cold...', after: 'My Armadrill keeps sniffing at the corner where the long tunnel comes down to meet the low passage. Rocks don\'t sniff at nothing.' });
  T('mg_ace', 'Ace Tamer', 'Mara', 'ace_f', [['nightwing', 35], ['frostemper', 35]], { intro: 'Only strong Tamers make it through Mt. Glacia!', defeat: 'You\'ll make it.', after: 'Skyreach is just ahead. The Crane tower is the tallest building in the city.' }, { money: 55, ai: 3 });
  T('mg_vet', 'Veteran', 'Holt', 'veteran', [['glaciursa', 36], ['bouldrok', 36]], { intro: 'Forty years I\'ve walked this pass. Show me what you\'ve got!', defeat: 'Forty years, and still learning.', after: 'A Link Cord makes Bouldrok evolve. They sell them in Skyreach.' }, { money: 60, ai: 3 });
  // -------------------------------------------------------------- CRANE HQ
  T('hq_grunt1', 'Hollow Grunt', 'Grunt', 'grunt', [['gnawmaw', 36], ['sludgor', 36]], { intro: 'Intruder! There\'s an intruder on the first floor!', defeat: 'Security failed...', after: '...' }, grunt());
  T('hq_grunt2', 'Hollow Grunt', 'Grunt', 'grunt_f', [['nightwing', 37], ['banditoon', 37]], { intro: 'You won\'t reach the Director!', defeat: 'You got past me... but that\'s only the start.', after: '...' }, grunt());
  T('hq_sci1', 'Hollow Scientist', 'Dr. Voss', 'scientist', [['dynamech', 37], ['gearling', 36]], { intro: 'The Chorus Engine\'s calibration must not be interrupted!', defeat: 'Calibration... interrupted.', after: 'The Engine gathers every bond in Solmere into a single song. Hers.' }, grunt());
  T('hq_grunt3', 'Hollow Grunt', 'Grunt', 'grunt', [['stormhound', 37], ['waspear', 37]], { intro: 'You\'re the one everyone\'s been whispering about!', defeat: 'The whispers didn\'t do you justice.', after: '...' }, grunt());
  T('hq_sci2', 'Hollow Scientist', 'Dr. Reyes', 'scientist', [['chimelle', 38], ['dynamech', 38]], { intro: 'Do you know what Resonance could do in the right hands?', defeat: 'Not in these hands, it seems.', after: 'I joined Crane to help Echoes that couldn\'t bond. I don\'t know when it became this.' }, grunt());
  T('grey2', 'Hollow Admin', 'Grey', 'grey', [['dynamech', 42], ['sludgor', 42], ['armadrill', 43]], { intro: '', defeat: 'An unacceptable margin of error.' }, admin());
  T('lark2', 'Hollow Admin', 'Lark', 'lark', [['nightwing', 43], ['waspear', 43], ['banditoon', 44]], { intro: '', defeat: 'Not again! Why can\'t I ever beat you?!' }, admin());
  T('lark2w', 'Hollow Admin', 'Lark', 'lark', [['waspear', 43], ['banditoon', 44]], { intro: '', defeat: 'Not again! Why can\'t I ever beat you?!' }, admin());   // Wren went in alone: their fight at the cells took her Nightwing
  T('crane1', 'Director', 'Vesper Crane', 'crane', [['dynamech', 41, { moves: ['flashcannon', 'ironhead', 'ironwall', 'voltdash'] }], ['chimelle', 41, { moves: ['playrough', 'reflect', 'staticwave', 'flashcannon'] }], ['masquerail', 42, { moves: ['shadowball', 'psychic', 'calmmind', 'hypnosis'] }], ['stormhound', 43, { item: 'lifegem', moves: ['thunderfang', 'crunch', 'surgetackle', 'voltdash'] }]],
    { intro: '', defeat: 'So your bond is real. Real enough to hurt me.' }, admin({ money: 150, ai: 4, music: 'crane_battle', resonate: true, env: 'hq', items: { hyperpotion: 2 } }));
  // --------------------------------------------------------- SKYREACH GYM
  T('sg_1', 'Dragon Tamer', 'Ryu', 'dragontamer', [['stratowyrm', 40, { abil: 2, moves: ['tailwind', 'dragonpulse', 'airslash', 'twister'] }], ['nimbling', 39]], { intro: 'Feel that? That\'s the master\'s wind. Dragons answer only to the strong!', defeat: 'I\'m not strong enough... yet.', after: 'The master\'s wind blows four breaths, then it\'s gone. Count them. The ones who beat him hide from it, or answer it with a wind of their own. Someone dropped a Tailwind disc behind the Battle Spire, you know. It\'s been there all year.' }, gymO());
  T('sg_2', 'Dragon Tamer', 'Mei', 'dragontamer', [['stratowyrm', 40, { abil: 2, moves: ['dragonclaw', 'airslash', 'braceup', 'dragonpulse'] }], ['riptalon', 41]], { intro: 'Nothing has ever knocked my Stratowyrm down in one blow. Try it!', defeat: 'And I never will.', after: 'Did you feel your first hit slide off my Stratowyrm? The master\'s Tempestral has the same scales. They only shine while it\'s unhurt. Crack them with anything, even a scratch, and the next blow lands properly.' }, gymO());
  T('sg_3', 'Dragon Tamer', 'Oro', 'dragontamer', [['raptorix', 41], ['tempestral', 41, { moves: ['wyrmdance', 'dragonclaw', 'airslash', 'aerialace'] }]], { intro: 'Kaelen trained me himself! Prepare yourself!', defeat: 'Kaelen will be proud of you.', after: 'When a Tempestral starts to dance, it doesn\'t stop until everything in front of it is down. Don\'t trade blows with it. A Roar sends it back to its Orb, and the dance goes with it. The Galvan shop used to sell that disc.' }, gymO());
  T('kaelen', 'Warden', 'Kaelen', 'kaelen', [['stratowyrm', 42, { abil: 2, moves: ['tailwind', 'dragonpulse', 'airslash', 'dragonclaw'] }], ['riptalon', 42, { moves: ['crunch', 'cascade', 'dragonclaw', 'ironhead'] }], ['raptorix', 42, { moves: ['crunch', 'dragonclaw', 'rockslide', 'ironhead'] }], ['tempestral', 43, { abil: 2, item: 'dragonfang', moves: ['wyrmdance', 'dragonclaw', 'airslash', 'earthquake'] }]],
    { intro: '', defeat: 'The storm has passed. You are worthy of the dragons\' respect.', retry: 'Back so soon? Good. The storm doesn\'t care who you are. Only whether you\'re still standing when it stops.' }, leader({ resonate: true }));   // his plan: the wind (Stratowyrm's Tailwind), then the scales and the dance (Tempestral: Multiscale, Wyrm Dance); see SC.kaelen
  // --------------------------------------------------------------- ROUTE 6
  T('r6_sailor', 'Sailor', 'Hank', 'sailor', [['crustank', 40], ['riptalon', 40]], { intro: 'The Mere has been restless lately!', defeat: 'Calm seas now.', after: 'The lighthouse went dark last night, for the first time in my life. The whole sea felt it.' });
  T('r6_swim1', 'Swimmer', 'Marina', 'swimmer_f', [['jellume', 41], ['tidetail', 41]], { intro: 'Going to the Lodestar? You\'ll have to beat me first!', defeat: 'Go. Hurry.', after: 'One of the Hollow on the north islet dropped a Skill Disc and was too scared of the Director to go back for it. Umbral Pulse. He said her masked Echoes can\'t stand the dark.' });
  T('r6_swim2', 'Swimmer', 'Finn', 'swimmer', [['lilyking', 41]], { intro: 'I swim this route every day to train!', defeat: 'Tomorrow I\'ll swim it twice.', after: 'My Lilyking is the slowest thing in the Mere. Everyone laughs. But I saw the Director\'s masked Echo twist the air once, so the slow ones went first. In a room like that, my Lilyking would be the fastest thing alive.' });
  T('r6_ace', 'Ace Tamer', 'Solen', 'ace', [['galeclaw', 42], ['crustank', 42], ['lumitail', 42]], { intro: 'I\'ve heard the Champion has an eye on you. Let me see why.', defeat: 'I see now.', after: 'Walk with your Echoes, and your bond will grow. Some evolve only once they trust you completely.' }, { money: 55, ai: 3 });
  T('r6_grunt', 'Hollow Grunt', 'Grunt', 'grunt', [['banditoon', 42], ['nightwing', 42]], { intro: 'The Director\'s moment is at hand! You shall not pass!', defeat: 'I... fell.', after: 'The Director\'s Chimelle puts up a wall before anyone else can move. Punches just bounce off it. ...Why am I telling you this?' }, grunt());
  // ---------------------------------------------------------- LIGHTHOUSE
  T('lh_grunt1', 'Hollow Grunt', 'Grunt', 'grunt', [['sludgor', 43], ['gnawmaw', 43]], { intro: 'The Engine is almost charged!', defeat: 'Charge... interrupted...', after: 'Five turns. That\'s how long the Director\'s twisted room holds. I timed it in training. Five turns, and then everything is the right way round again.' }, grunt());
  T('lh_grunt2', 'Hollow Grunt', 'Grunt', 'grunt_f', [['nightwing', 43], ['dynamech', 44]], { intro: 'Can you hear it? The song is fading...', defeat: 'I don\'t want the song to fade...', after: 'Maybe we\'re on the wrong side. Maybe we have been for a long time.' }, grunt());
  T('lh_sci', 'Hollow Scientist', 'Dr. Pell', 'scientist', [['dynamech', 44], ['chimelle', 44]], { intro: 'We meet again! My readings predicted you would come!', defeat: 'My readings predicted this, too. I hoped they were wrong.', after: 'A Reflect halves any blow that lands with a body. A beam of pure energy passes straight through it. I told the Director so. She said nobody would ever get close enough for it to matter.' }, grunt());
  T('grey3', 'Hollow Admin', 'Grey', 'grey', [['dynamech', 47], ['sludgor', 48], ['armadrill', 48], ['craggolem', 48]], { intro: '', defeat: 'Calculations complete. We were wrong.' }, admin({ items: { hyperpotion: 1 } }));
  T('lark3', 'Hollow Admin', 'Lark', 'lark', [['nightwing', 48], ['waspear', 48], ['banditoon', 49], ['stormhound', 49]], { intro: '', defeat: '...All right. Go. Stop her.' }, admin({ items: { hyperpotion: 1 } }));
  // Crane's plan (GRAVITY_PLAN item 2): a Prankster wall first, then the masks twist the room so her slow machines strike first for
  // five turns, and her Stormhound waits for the room to come straight. Answers, each pointed to twice on the way up: beams go
  // through a Reflect (the Route 6 grunt, Dr. Pell), a slow Echo of your own or five turns waited out (Finn, the 1F grunt), and the
  // dark for her masks (Marina, the Umbral Pulse disc on the north islet, the grunt by the door). Lark (vars.larkCave 2) takes her medicine.
  T('crane2', 'Director', 'Vesper Crane', 'crane', [['chimelle', 47, { moves: ['reflect', 'playrough', 'flashcannon', 'staticwave'] }], ['masquerail', 48, { moves: ['twistroom', 'shadowball', 'psychic', 'calmmind'] }],
    ['coffret', 48, { moves: ['shadowclaw', 'ironhead', 'crunch', 'shadowsneak'] }], ['dynamech', 49, { moves: ['flashcannon', 'thunderbolt', 'ironhead', 'voltdash'] }], ['stormhound', 51, { item: 'lifegem', moves: ['thunderfang', 'crunch', 'surgetackle', 'voltdash'] }]],
    { intro: '', defeat: 'Lumi... I\'m sorry.' }, admin({ money: 200, ai: 4, music: 'crane_battle', resonate: true, aceLast: true, env: 'lighthouse', items: { hyperpotion: 2, fullrestore: 1 } }));
  G.TRAINERS.crane2l = { ...G.TRAINERS.crane2, items: {} };   // Lark emptied her coat on the stairs
  // ---------------------------------------------------------- VICTORY ROAD
  // ---------------------------------------------------------- VICTORY ROAD
  // The last road points at the Conclave (GRAVITY_PLAN item 2): each of the four and Sable is described twice before you
  // reach them, once down here and once at the Conclave, and never by type. The road's Discs are the answers (Psychic for
  // Rook, Focus Burst and Moon Burst for Nyx), each named by the Tamer who stands nearest it.
  T('vr_ace1', 'Ace Tamer', 'Vale', 'ace', [['stratowyrm', 46], ['cinderwing', 47], ['crustank', 47]], { intro: 'Only the best reach Victory Road. Are you one of them?', defeat: 'You are.', after: 'Ferrum lost to me once, you know. Once. His armour went soft the day my Cinderwing breathed on it. He\'s kept a sea creature in the back ever since, for Tamers like me.' }, { money: 60, ai: 3 });
  T('vr_ace2', 'Ace Tamer', 'Iris', 'ace_f', [['aurorelle', 47], ['luminelle', 47], ['hootsage', 48]], { intro: 'Grace and power! Shall we dance?', defeat: 'What a lovely battle. I lost beautifully.', after: 'Nyx never hits hard. She borrows. The harder your Echo hits, the harder it\'s hit back, and her ghost lion burns anything that swings. My Luminelle only ever sang at them. They hated that. There\'s a Moon Burst disc in the hollow south of the lake, if yours can learn it.' }, { money: 60, ai: 3 });
  T('vr_vet', 'Veteran', 'Bram', 'veteran', [['craggolem', 48], ['glaciursa', 48], ['slumbruin', 48]], { intro: 'I\'ve challenged the Conclave nine times. You get one battle with me.', defeat: 'Perhaps you\'ll make it on your first try.', after: 'Seraphine hangs a curtain of light before anyone moves. Then her Echoes sit behind it and think, and every thought makes the next one stronger. Hit hard before the second thought, or bring something that breaks curtains.' }, { money: 70, ai: 3 });
  T('vr_bb', 'Blackbelt', 'Kenji', 'blackbelt', [['grandmonk', 47], ['scarabrute', 48], ['thornhare', 48]], { intro: 'Rook of the Conclave is my master! HYAH!', defeat: 'Master Rook would say I have much still to learn.', after: 'Master Rook braces before he strikes. Once, twice, and then no fist lands clean on him. He says he only fears two kinds of fighter: the ones who never lay a hand on him, and the ones who think. ...There\'s a Psychic disc on the north shore of the lake below us. I can\'t use it. I don\'t think.' }, { money: 60, ai: 3 });
  T('vr_dt', 'Dragon Tamer', 'Zola', 'dragontamer', [['riptalon', 48], ['raptorix', 49]], { intro: 'Kaelen\'s old rival, at your service!', defeat: 'Tell Kaelen I said hello.', after: 'Sable taught Kaelen to call the wind. Kaelen taught me. Guess what the Champion opens with. And there\'s a Focus Burst disc on the ledge east of this lake: Nyx\'s lot never see a punch like that coming, because it isn\'t one.' }, { money: 60, ai: 3 });
  // ------------------------------------------------------------ CONCLAVE
  // Each of the four has a plan (setup: the AI sets up the moment an Echo comes in fresh, see ai.js), and each plan has answers:
  //   Rook braces (Atk and Def) and hits through it: beams and thinking (the Psychic disc, Kenji; the veteran outside), a Roar.
  //   Seraphine: a Light Screen first, then Calm Minds behind it and Stored Power: strike before the second thought, Wall
  //     Breaker, or the dark (her Psychic moves can't touch it; Bram, the challenger in the hall).
  //   Nyx borrows your strength (Foul Play), weakens and slips away (Parting Taunt), burns strikers (Wisp Flame, a Prankster):
  //     beams, Moon Burst, Focus Burst (Iris, Zola), and a Dark Echo her tricks can't touch (the challenger in the hall).
  //   Ferrum lays Shard Trap first and hides behind a Spiked Helm, with a sea creature in the back for fire: pick a lead and stay, and heat (Vale, the veteran outside).
  T('rook', 'Conclave', 'Rook', 'rook', [['scarabrute', 54, { item: 'sunberry', moves: ['braceup', 'closecombat', 'rockslide', 'megahorn'] }], ['thornhare', 55, { item: 'lifegem', moves: ['braceup', 'closecombat', 'leafblade', 'timberslam'] }], ['frostemper', 55, { item: 'blackbelt', moves: ['braceup', 'closecombat', 'icicledrop', 'drainpunch'] }], ['grandmonk', 57, { item: 'leftovers', moves: ['braceup', 'drainpunch', 'zenstrike', 'closecombat'] }]],
    { intro: 'I am Rook, the first wall of the Conclave. I have broken stone with my fists, and my heart with defeat. Neither made me quit. Show me your resolve!', defeat: 'A mighty will. Go on. The next wall stands higher.' }, elite({ setup: true, items: { fullrestore: 1 } }));
  T('seraphine', 'Conclave', 'Seraphine', 'seraphine', [['chimelle', 53, { item: 'lumenberry', moves: ['lightscreen', 'playrough', 'moonblast', 'staticwave'] }], ['hootsage', 54, { item: 'sunberry' }], ['lumitail', 54, { item: 'twistedspoon', moves: ['calmmind', 'storedpower', 'psychic', 'shadowball'] }], ['masquerail', 56, { item: 'leftovers', moves: ['psychic', 'shadowball', 'calmmind', 'twistroom'] }]],
    { intro: 'I\'ve already seen how this battle ends, young Tamer. But the future is only a guess until someone makes it true. Let\'s find out together.', defeat: 'How wonderful. I was wrong. It\'s been so long since I was wrong.' }, elite({ setup: true, items: { fullrestore: 1 } }));
  T('nyx', 'Conclave', 'Nyx', 'nyx', [['banditoon', 52, { item: 'sunberry', abil: 2, moves: ['partingtaunt', 'foulplay', 'ambush', 'doubleedge'] }], ['nightwing', 53, { item: 'sharpbeak' }], ['umbratail', 53, { item: 'leftovers', moves: ['taunt', 'foulplay', 'darkpulse', 'moonlight'] }], ['gnawmaw', 54, { item: 'lifegem' }], ['phantomane', 55, { item: 'blackglasses', abil: 2, moves: ['wispflame', 'darkpulse', 'shadowball', 'nightslash'] }]],
    { intro: '...You want to know why I battle in the dark? Because it\'s honest. Nothing hides here. Not even you.', defeat: '...Heh. You shine too brightly for the dark.' }, elite({ items: { fullrestore: 1 } }));
  T('ferrum', 'Conclave', 'Ferrum', 'ferrum', [['armadrill', 51, { item: 'leftovers', abil: 2, moves: ['shardtrap', 'earthquake', 'ironhead', 'drillrun'] }], ['coffret', 50, { item: 'spikedhelm', moves: ['ironhead', 'shadowclaw', 'crunch', 'shadowsneak'] }], ['chimelle', 51, { item: 'sunberry' }], ['dynamech', 52, { item: 'magnet', moves: ['thunderbolt', 'flashcannon', 'discharge', 'voltdash'] }], ['tidalrus', 53, { item: 'metalcoat', moves: ['anchorslam', 'cascade', 'icicledrop', 'ironhead'] }]],
    { intro: 'I forged my first Echo\'s armour from scrap when I was your age. Every dent tells a story. Let\'s add one more.', defeat: 'A fine dent indeed. The Champion is waiting, young one.' }, elite({ setup: true, items: { fullrestore: 2 } }));
  // ------------------------------------------------------------ POST-GAME
  // Starfall Peak: a ladder from the Champion (58) up to the Wanderer (72+) at the summit.
  T('sf_ace', 'Ace Tamer', 'Corin', 'ace', [['stratowyrm', 62], ['frostemper', 62], ['chimelle', 63]], { intro: 'So you\'re the new Champion. Up here, titles don\'t keep you warm.', defeat: 'Warm enough, I suppose.', after: 'Something walks the ridge at night. It looks like a comet that forgot to fall.' }, { money: 80, ai: 3, env: 'snow' });
  T('sf_vet', 'Veteran', 'Maude', 'veteran', [['glaciursa', 64], ['hootsage', 64], ['craggolem', 65], ['cinderwing', 65]], { intro: 'I climbed this peak before your parents were born. Let\'s see how you climb.', defeat: 'Good legs. Better heart.', after: 'There\'s someone at the very top who never speaks. Bring your best six, and bring plenty of Restores.' }, { money: 90, ai: 4, env: 'snow' });
  T('sf_dt', 'Dragon Tamer', 'Aster', 'dragontamer', [['riptalon', 66], ['nightwing', 66], ['raptorix', 67], ['phantomane', 68]], { intro: 'The comet left dragons in its wake, they say. I came to find out if it\'s true.', defeat: 'Not the dragon I was looking for... but a dragon all the same.', after: 'The one at the summit has beaten me eleven times. I keep count so I don\'t give up.' }, { money: 100, ai: 4, env: 'snow' });
  T('wanderer', 'Wanderer', '???', 'wanderer', [['riptalon', 72, { item: 'leftovers' }], ['slumbruin', 72, { item: 'sunberry' }], ['sylvantler', 73, { item: 'lifegem' }], ['tidalrus', 73, { item: 'leftovers' }], ['solarynx', 73, { item: 'focuslens' }], ['tempestral', 75, { item: 'lifegem' }]],
    { intro: '...', defeat: '......!' }, { money: 300, ai: 4, boss: true, resonate: true, music: 'wanderer', victory: 'victory_champion', noRematch: true, env: 'snow' });
})();
