'use strict';
// ============================================================================
//  Trainers of Solmere. party: [{sp, lvl, moves?, item?, nature?, abil?}]
// ============================================================================
(function () {
  const T = (id, cls, name, look, party, lines = {}, o = {}) => { G.TRAINERS[id] = { cls, name, look, party: party.map(([sp, lvl, extra]) => ({ sp, lvl, ...(extra || {}) })), money: o.money || 30, ai: o.ai !== undefined ? o.ai : 2, ...lines, ...o }; };
  const gymO = (o = {}) => ({ money: 45, ai: 2, env: 'gym', ...o });
  const leader = (o) => ({ money: 120, ai: 3, boss: true, music: 'gym_battle', victory: 'victory_gym', noRematch: true, env: 'gym', ...o });
  const grunt = (o = {}) => ({ money: 40, ai: 2, music: 'villain_battle', encounterMusic: 'encounter_villain', noRematch: true, ...o });
  const admin = (o = {}) => ({ money: 90, ai: 3, boss: true, music: 'admin_battle', encounterMusic: 'encounter_villain', noRematch: true, ...o });
  const elite = (o = {}) => ({ money: 150, ai: 4, boss: true, music: 'elite', victory: 'victory_gym', noRematch: true, env: 'league', resonate: true, ...o });

  // ------------------------------------------------------------ ROUTE 1
  T('r1_kid', 'Kid', 'Timmy', 'kid', [['nibbit', 3]], { intro: 'My Nibbit can chew through anything! Wanna see? You don\'t get a choice!', defeat: 'It chewed through my confidence.', after: 'Nibbit\'s teeth never stop growing. Mine stopped. I\'m eight. It\'s fine.' });
  T('r1_lass', 'Lass', 'Poppy', 'lass', [['pipwing', 3], ['mossbun', 4]], { intro: 'First Echo? Me too! Sort of! I borrowed my sister\'s. Don\'t tell her!', defeat: 'Beginner\'s luck! That\'s what I\'m telling my sister.', after: 'Hold Shift to run! I run everywhere! I ran into a tree once!' });
  // ------------------------------------------------------- FERNWICK GYM
  T('fg_1', 'Gardener', 'Rosa', 'farmer', [['mossbun', 9], ['shroomie', 10]], { intro: 'Every flower in here was planted by hand! Step on one and Juniper WILL know.', defeat: 'My petals... wilted.', after: 'Fire burns grass. Water just makes us bigger. Choose wisely.' }, gymO());
  T('fg_2', 'Gardener', 'Tobin', 'farmer', [['shroomie', 10], ['mossbun', 10]], { intro: 'Juniper\'s the gentlest Warden in Solmere. She once made a Hiker cry with a compliment.', defeat: 'Okay. You\'re the real deal.', after: 'Leech Seed. Tiny. Rude. Adds up.' }, gymO());
  T('juniper', 'Warden', 'Juniper', 'juniper', [['mossbun', 11, { moves: ['vinewhip', 'quickstrike', 'tailwhip', 'bulletseed'] }], ['shroomie', 12, { moves: ['megadrain', 'stunspore', 'poisonsting', 'absorb'] }], ['fawnbloom', 14, { item: 'oranberry', moves: ['razorleaf', 'leechseed', 'charmleaf', 'growl'] }]],
    { intro: '', defeat: 'Oh my. You and your partners bloom together beautifully. I hate it. I love it.' }, leader({ items: { superpotion: 1 } }));
  // ------------------------------------------------------------ ROUTE 2
  T('r2_bug', 'Bug Maniac', 'Wes', 'bugmaniac', [['grubbit', 7], ['grubbit', 7], ['cocoonet', 8]], { intro: 'Behold my ARMY of future Aurorymoths!', defeat: 'My army... is still in training. It\'s three grubs.', after: 'Grubbit evolves fast. Level 7, then 10. Blink and it\'s a moth.' });
  T('r2_hiker', 'Hiker', 'Dale', 'hiker', [['pebblin', 9], ['pebblin', 10]], { intro: 'HAH! ROCKS! Rocks are the best! Rocks never let you down!', defeat: 'I\'ve been ground down!', after: 'Pebblin love to sunbathe. So do I. We sunbathe together. It\'s our thing.' });
  T('r2_lass', 'Lass', 'Juno', 'lass', [['glimmer', 9], ['pipwing', 10]], { intro: 'My Glimmer glows when it\'s happy! Let\'s make it glow!', defeat: 'It\'s still glowing... at YOU. Traitor.', after: 'Glimmer evolves when it really loves you. No stones. Just vibes.' });
  T('r2_twins', 'Twins', 'Ami & Mei', 'twins', [['nibbit', 9], ['mossbun', 9]], { intro: 'We battle together! Two on two! We also finish each other\'s—', defeat: '—sandwiches! We lost together!', after: 'Double battles are teamwork. Spread moves hit both foes at once!' }, { double: true, money: 25 });
  T('r2_kid', 'Kid', 'Leo', 'boy', [['stingle', 8], ['nibbit', 9]], { intro: 'Stingle\'s stinger is tiny but it HURTS!', defeat: 'Owww. Okay, it hurts both ways.', after: 'Poison wears off after battle here. My mom checked. Twice.' });
  // --------------------------------------------------------- WHISPERWOOD
  T('ww_bug', 'Bug Maniac', 'Kit', 'bugmaniac', [['beetlet', 11], ['stingle', 11]], { intro: 'Whisperwood is a bug paradise! Everything here has six legs or wants to!', defeat: 'Squashed...', after: 'Beetlet evolves into a brawler. It fights trees for fun.' });
  T('ww_ranger', 'Ranger', 'Ivy', 'ranger', [['mossbun', 11], ['glimmer', 12]], { intro: 'Rangers protect these woods. Prove you respect them!', defeat: 'You\'re kind to your Echoes. I can tell. They keep looking back at you.', after: 'The gray coats went toward the shrine. Hurry. Please.' });
  T('ww_mystic', 'Mystic', 'Wendel', 'mystic', [['wispurr', 12], ['oddowl', 12]], { intro: 'The trees whisper of a visitor... it\'s you. They said you\'d be taller.', defeat: 'The whispers were right about you.', after: 'Wispurr come out at night. Usually. They\'re not great with rules.' });
  T('ww_grunt1', 'Hollow Grunt', 'Grunt', 'grunt', [['nibbit', 11], ['blotch', 12]], { intro: 'Hollow business! Very official! Very legal! Go away!', defeat: 'Tch! The Director is gonna see this in the weekly report.', after: 'We\'re doing RESEARCH. With crowbars. It\'s a new field.' }, grunt());
  T('ww_grunt2', 'Hollow Grunt', 'Grunt', 'grunt_f', [['rascoon', 12], ['blotch', 13]], { intro: 'You beat my partner? Then you have to beat me too! That\'s how it works! I think!', defeat: 'Fine! We already got a shard! Mission... partially accomplished!', after: '...' }, grunt());
  // --------------------------------------------------------------- GALVAN
  T('gv_sailor', 'Sailor', 'Brody', 'sailor', [['clawdle', 15], ['flopfin', 14]], { intro: 'Ahoy! A battle to warm the blood! The sea air is FREEZING!', defeat: 'Sunk me like an anchor!', after: 'Old Salt Marv swears Flopfin turn into something terrifying. Nobody believes him. I kinda do.' });
  T('gv_worker', 'Worker', 'Mack', 'worker', [['gearling', 16], ['pebblin', 15]], { intro: 'Break time! Let\'s battle! Don\'t tell my supervisor!', defeat: 'Back to work, I guess. Worst break ever.', after: 'Crane Dynamics built half this city. Big company. Big secrets. Big free coffee, though.' });
  T('gg_1', 'Punk', 'Zed', 'punk', [['voltpup', 15], ['zipsquee', 16]], { intro: 'Ione\'s beats hit harder than lightning! So do I!', defeat: 'Feedback! Too much feedback!', after: 'Ground types don\'t even hear Electric moves. Just saying.' }, gymO());
  T('gg_2', 'Punk', 'Roxy', 'punk', [['gearling', 16], ['voltpup', 16]], { intro: 'Flip the right switches? Doesn\'t matter! You still have to get past me!', defeat: 'Short-circuited!', after: 'The barriers drop when you step on the glowing pads. I tell everyone. Nobody listens.' }, gymO());
  T('gg_3', 'Engineer', 'Faye', 'scientist', [['gearling', 17], ['jellume', 17]], { intro: 'I wired this gym myself. I know every trick!', defeat: 'I did not design THAT outcome.', after: 'Jellume eats Electric attacks. Literally. It\'s a whole thing.' }, gymO());
  T('ione', 'Warden', 'Ione', 'ione', [['voltpup', 17, { moves: ['spark', 'bite', 'joltnuzzle', 'staticwave'] }], ['gearling', 17, { moves: ['metalclaw', 'spark', 'staticwave', 'tackle'] }], ['zipsquee', 18, { moves: ['spark', 'aerialace', 'quickstrike', 'joltnuzzle'] }], ['jellume', 20, { item: 'sunberry', moves: ['bubblejet', 'spark', 'staticwave', 'zap'] }]],
    { intro: '', defeat: 'Mic drop! You remixed me!' }, leader({ items: { superpotion: 2 } }));
  // --------------------------------------------------------------- ROUTE 3
  T('r3_swim1', 'Swimmer', 'Kai', 'swimmer', [['clawdle', 16], ['lillipad', 16]], { intro: 'The water\'s perfect! So is my team!', defeat: 'Glub glub...', after: 'You\'ll surf someday. The Mere is HUGE. Bring sunscreen.' });
  T('r3_swim2', 'Swimmer', 'Nia', 'swimmer_f', [['jellume', 17]], { intro: 'Jellume! Light them up!', defeat: 'Dimmed...', after: 'Jellume blooms light up the harbor on summer nights. It\'s the best date spot. Not that I\'d know.' });
  T('r3_fisher', 'Fisher', 'Bo', 'fisher', [['flopfin', 12], ['flopfin', 14], ['flopfin', 16]], { intro: 'I only fish for the BEST. Behold! My Flopfin!', defeat: 'I\'ll keep believing in it!', after: 'Level 20. Old Salt Marv says something happens at level 20. I\'ve been waiting six years.' });
  T('r3_hiker', 'Hiker', 'Gus', 'hiker', [['digmole', 17], ['pebblin', 17]], { intro: 'These cliffs are my home turf!', defeat: 'Avalanche of defeat!', after: 'A hiker in Glimmer Cave needs help. Big guy. Bigger hammer. Tiny voice.' });
  T('r3_ace', 'Ace Tamer', 'Lyra', 'ace_f', [['gustling', 18], ['lillipad', 18], ['voltpup', 18]], { intro: 'Ace Tamers train with purpose. Show me yours!', defeat: 'Your purpose is VERY clear.', after: 'Give your team held items. A Sun Berry has saved my life. Emotionally.' }, { money: 50, ai: 3 });
  T('r3_kid', 'Kid', 'Pip', 'kid', [['pipwing', 15], ['gustling', 17]], { intro: 'Birds rule the sky AND this route!', defeat: 'Grounded! Literally!', after: 'Gustling becomes Galeclaw at 32. SO cool. I\'m counting the levels.' });
  // --------------------------------------------------------- GLIMMER CAVE
  T('gc_hiker', 'Hiker', 'Rocco', 'hiker', [['pebblin', 18], ['pebblin', 19]], { intro: 'Crystals everywhere! And trainers! My two favorite things!', defeat: 'Crushed like quartz!', after: 'The crystals hum when Echoes are near. Like they\'re saying hi.' });
  T('gc_grunt1', 'Hollow Grunt', 'Grunt', 'grunt', [['duskbat', 18], ['blotch', 19]], { intro: 'These crystals are Crane Dynamics property now! There\'s a sticker!', defeat: 'Aw, man.', after: 'The crystals store Resonance. That\'s what the nerds say. I just carry the crates.' }, grunt());
  T('gc_grunt2', 'Hollow Grunt', 'Grunt', 'grunt_f', [['rascoon', 19], ['gearling', 19]], { intro: 'Admin Lark said NOBODY gets past!', defeat: 'Lark\'s gonna yell at me. She yells in lowercase. It\'s worse.', after: '...' }, grunt());
  T('gc_sci', 'Hollow Scientist', 'Dr. Pell', 'scientist', [['gearling', 19], ['magmite', 19]], { intro: 'Your Echo\'s Resonance readings! Fascinating! Hold still!', defeat: 'The data... it\'s off the charts!', after: 'Resonance is just energy. It can be harvested. It WILL be harvested. That sounded evil. I meant it scientifically.' }, grunt());
  T('lark1', 'Hollow Admin', 'Lark', 'lark', [['duskbat', 19], ['stingle', 20], ['rascoon', 21, { item: 'oranberry' }]], { intro: '', defeat: 'UGH! Fine! Keep your stupid glowing rocks!' }, admin({ items: { potion: 1 } }));
  // ----------------------------------------------------------- CINDERVALE
  T('cg_1', 'Smith', 'Hal', 'worker', [['magmite', 21], ['emberjay', 22]], { intro: 'Welcome to the Forge! Mind the lava! It minds you!', defeat: 'Quenched!', after: 'Water, Ground and Rock cool us right off.' }, gymO());
  T('cg_2', 'Smith', 'Ada', 'artist', [['emberjay', 22], ['magmite', 22]], { intro: 'Brann taught me to temper steel AND spirit!', defeat: 'My spirit needs more tempering.', after: 'Brann\'s ace Resonates. Save something strong for the end!' }, gymO());
  T('cg_3', 'Blackbelt', 'Jo', 'blackbelt', [['scrapmonk', 23]], { intro: 'HYAH! Fire in my fists! Not literally! Okay, a little!', defeat: 'I have been... extinguished.', after: 'Scrapmonk becomes Grandmonk at 30. Peace and punches.' }, gymO());
  T('brann', 'Warden', 'Brann', 'brann', [['magmite', 23, { moves: ['flamerush', 'rocktomb', 'ancientpower', 'tackle'] }], ['emberjay', 24, { moves: ['flamerush', 'wingslash', 'quickstrike', 'aerialace'] }], ['scrapmonk', 24, { moves: ['drainpunch', 'chop', 'braceup', 'rapidjab'] }], ['emberail', 26, { item: 'charcoal', moves: ['firefang', 'flamerush', 'bite', 'quickstrike'] }]],
    { intro: '', defeat: 'HAAA! You\'ve got fire in you, kid! The GOOD kind!' }, leader({ resonate: true, items: { superpotion: 2 } }));
  // --------------------------------------------------------------- ROUTE 4
  T('r4_hiker', 'Hiker', 'Ben', 'hiker', [['bouldrok', 25], ['digmole', 24]], { intro: 'Ash in my beard! Rocks in my heart!', defeat: 'Buried!', after: 'Cindervale\'s hot springs fix everything. Except losing. I tried.' });
  T('r4_ace', 'Ace Tamer', 'Rin', 'ace', [['emberjay', 25], ['lillipad', 25], ['zipsquee', 25]], { intro: 'A balanced team is a winning team!', defeat: 'I need more balance. In battle. In life.', after: 'EV training! Beat certain Echoes to grow certain stats. It\'s like a gym membership that works.' }, { money: 50, ai: 3 });
  T('r4_punk', 'Punk', 'Vic', 'punk', [['rascoon', 24], ['stingle', 24], ['waspear', 25]], { intro: 'This road\'s got a toll. You pay in battles.', defeat: 'Toll waived. Just go. Please go.', after: '...' });
  T('r4_bb', 'Blackbelt', 'Taro', 'blackbelt', [['scrapmonk', 25], ['thornhare', 26]], { intro: 'I train on this ash road every morning! My lungs are very confused!', defeat: 'My training is incomplete!', after: 'Thornhare kicks harder than a Grandmonk punches. I have the bruises to prove it.' });
  T('r4_mystic', 'Mystic', 'Luz', 'mystic', [['maskling', 25], ['wispurr', 25]], { intro: 'The spirits of Duskmere drift this far... and they\'re gossiping about you.', defeat: 'The spirits approve of you.', after: 'Wispurr evolves with a Dusk Stone. The lamplighter in Duskmere has one.' });
  // ---------------------------------------------------------------- RUINS
  T('ru_grunt1', 'Hollow Grunt', 'Grunt', 'grunt', [['gnawmaw', 26], ['blotch', 26]], { intro: 'The Tide Key is OURS! Get lost!', defeat: 'Admin Grey is going to look at me with that face.', after: '...' }, grunt());
  T('ru_grunt2', 'Hollow Grunt', 'Grunt', 'grunt_f', [['duskbat', 26], ['rascoon', 27]], { intro: 'YOU again?! There\'s a photo of you in our break room!', defeat: 'How are you THIS strong?!', after: 'The key opens something under the Lodestar. That\'s all they told me. They never tell me anything.' }, grunt());
  T('ru_grunt3', 'Hollow Grunt', 'Grunt', 'grunt', [['gearling', 27], ['sludgor', 28]], { intro: 'Last line of defense! For the Director! For the dental plan!', defeat: 'Line... breached...', after: '...' }, grunt());
  T('grey1', 'Hollow Admin', 'Grey', 'grey', [['gearling', 27], ['sludgor', 28], ['armadrill', 29, { item: 'sunberry' }]], { intro: '', defeat: 'Interesting. Your variance is statistically improbable.' }, admin({ items: { superpotion: 1 } }));
  // ------------------------------------------------------------ DUSK GYM
  T('dg_1', 'Mystic', 'Rue', 'mystic', [['wispurr', 27], ['maskling', 28]], { intro: 'Boo.', defeat: 'That was... supposed to scare you.', after: 'Normal and Fighting moves pass right through ghosts. Rude of them.' }, gymO());
  T('dg_2', 'Mystic', 'Sol', 'mystic', [['duskbat', 28], ['maskling', 28]], { intro: 'In darkness, only the brave see clearly. Also, I stubbed my toe.', defeat: 'You are brave indeed.', after: 'Dark moves hit Ghosts super effectively.' }, gymO());
  T('dg_3', 'Mystic', 'Cass', 'mystic', [['coffret', 29]], { intro: 'Did you think I was a treasure chest? Hehehe...', defeat: 'Snap!', after: 'Coffret hide in item balls. Be careful what you pick up. Some things pick you up.' }, gymO());
  T('mireille', 'Warden', 'Mireille', 'mireille', [['wispurr', 29, { moves: ['hex', 'confuseray', 'bite', 'shadowsneak'] }], ['maskling', 30, { moves: ['psybeam', 'hex', 'hypnosis', 'nightshade'] }], ['phantomane', 31, { moves: ['shadowclaw', 'bite', 'wispflame', 'hex'] }], ['masquerail', 32, { item: 'spelltag', moves: ['shadowball', 'psybeam', 'calmmind', 'hypnosis'] }]],
    { intro: '', defeat: 'The candle flickers... and still it burns. As do you.' }, leader({ resonate: true, items: { hyperpotion: 1, superpotion: 1 } }));
  // --------------------------------------------------------------- ROUTE 5
  T('r5_swim1', 'Swimmer', 'Tess', 'swimmer_f', [['lillipad', 28], ['jellume', 29]], { intro: 'You can surf? Then you can battle!', defeat: 'Washed out!', after: 'The islets hide items. Check every single one. Yes, that one too.' });
  T('r5_swim2', 'Swimmer', 'Rob', 'swimmer', [['mireel', 29], ['clawdle', 28]], { intro: 'Race you to the next islet! After this battle!', defeat: 'You\'d win the race too, probably.', after: 'Mireel\'s ability ignores stat boosts. Great counter to show-offs.' });
  T('r5_swim3', 'Swimmer', 'Coral', 'swimmer_f', [['crustank', 30]], { intro: 'My Crustank is basically a fortress with legs!', defeat: 'The walls came down.', after: '...' });
  T('r5_fisher', 'Fisher', 'Nell', 'fisher', [['flopfin', 25], ['riptalon', 30]], { intro: 'Everybody laughs at Flopfin. NOBODY laughs at THIS.', defeat: 'Fine. Laugh.', after: 'Patience. That\'s the secret. Patience and Flopfin.' });
  T('r5_couple', 'Couple', 'Jan & Lee', 'lady', [['lillipad', 29], ['mireel', 29]], { intro: 'We do everything together! Even battling! Especially battling!', defeat: 'At least we lost together.', after: 'Double battles need a plan for both slots. We had half a plan. Each.' }, { double: true, money: 35 });
  T('r5_ace', 'Ace Tamer', 'Dom', 'ace', [['tidetail', 31], ['gustling', 30], ['lillipad', 30]], { intro: 'I\'ve been waiting on this islet for a worthy opponent! For three days!', defeat: 'Worth the wait!', after: 'Shiftail evolves seven different ways. I picked Water. Obviously.' }, { money: 50, ai: 3 });
  // ------------------------------------------------------------ FROSTPEAK
  T('fp_skier1', 'Skier', 'Kris', 'skier', [['pengrost', 32], ['snowlet', 32]], { intro: 'Fresh powder! Fresh challenger!', defeat: 'Wiped out!', after: 'Sigrid\'s gym is all ice. Slide carefully. Or dramatically.' });
  T('fp_skier2', 'Skier', 'Anya', 'skier', [['icicub', 33], ['pengrost', 33]], { intro: 'Race you down the mountain! Wait, battle first!', defeat: 'You\'re fast. Unreasonably fast.', after: '...' });
  T('ig_1', 'Skier', 'Bjorn', 'skier', [['pengrost', 33], ['icicub', 34]], { intro: 'Did you slide into the right spot? Doesn\'t matter!', defeat: 'I\'m on thin ice.', after: 'Fire, Fighting, Rock and Steel all crack ice.' }, gymO());
  T('ig_2', 'Skier', 'Lin', 'skier', [['snowlet', 34], ['pengrost', 34]], { intro: 'Sigrid\'s waiting at the summit! She\'s doing lunges!', defeat: 'Avalanche!', after: 'Snow boosts Ice types\' Defense. Plan for it.' }, gymO());
  T('sigrid', 'Warden', 'Sigrid', 'sigrid', [['aurorelle', 36, { moves: ['icebeam', 'moonlight', 'charmvoice', 'auroraray'] }], ['frostemper', 36, { moves: ['icicledrop', 'drainpunch', 'iceshard', 'braceup'] }], ['glaciursa', 37, { moves: ['icicledrop', 'earthquake', 'slash', 'icefang'] }], ['frosttail', 39, { item: 'nevermeltice', moves: ['icebeam', 'frostbreath', 'snowfall', 'swift'] }]],
    { intro: '', defeat: 'INCREDIBLE! Like the first morning after a blizzard!' }, leader({ resonate: true, items: { hyperpotion: 2 }, weather: 'snow' }));
  // ----------------------------------------------------------- MT. GLACIA
  T('mg_hiker', 'Hiker', 'Olaf', 'hiker', [['bouldrok', 34], ['armadrill', 35]], { intro: 'Brr! A battle will warm us up!', defeat: 'Still cold. Still lost.', after: 'Push the boulders into the holes to make a path. It\'s like a puzzle, but heavier.' });
  T('mg_ace', 'Ace Tamer', 'Mara', 'ace_f', [['nightwing', 35], ['frostemper', 35]], { intro: 'Only strong Tamers make it through Glacia!', defeat: 'You\'ll make it.', after: 'Skyreach is just ahead. Crane HQ is the tallest tower. You can\'t miss it. It wants you to look at it.' }, { money: 55, ai: 3 });
  T('mg_vet', 'Veteran', 'Holt', 'veteran', [['glaciursa', 36], ['bouldrok', 36]], { intro: 'Forty years on this pass. Show me what you\'ve got!', defeat: 'Forty years, and still learning.', after: 'A Link Cord makes Bouldrok evolve. Skyreach sells them. Overpriced, but it works.' }, { money: 60, ai: 3 });
  // -------------------------------------------------------------- CRANE HQ
  T('hq_grunt1', 'Hollow Grunt', 'Grunt', 'grunt', [['gnawmaw', 36], ['sludgor', 36]], { intro: 'Intruder! Intruder on floor one! This is not a drill! Is it a drill?!', defeat: 'Security failed...', after: '...' }, grunt());
  T('hq_grunt2', 'Hollow Grunt', 'Grunt', 'grunt_f', [['nightwing', 37], ['banditoon', 37]], { intro: 'You won\'t reach the Director!', defeat: 'You reached... me. And beat me. That\'s step one, I guess.', after: '...' }, grunt());
  T('hq_sci1', 'Hollow Scientist', 'Dr. Voss', 'scientist', [['dynamech', 37], ['gearling', 36]], { intro: 'The Chorus Engine calibration must NOT be interrupted!', defeat: 'Calibration... interrupted.', after: 'The Engine forces every bond in Solmere into one frequency. Hers.' }, grunt());
  T('hq_grunt3', 'Hollow Grunt', 'Grunt', 'grunt', [['stormhound', 37], ['waspear', 37]], { intro: 'You\'re the kid everyone\'s whispering about!', defeat: 'The whispers undersold you.', after: '...' }, grunt());
  T('hq_sci2', 'Hollow Scientist', 'Dr. Reyes', 'scientist', [['chimelle', 38], ['dynamech', 38]], { intro: 'Do you know what Resonance could do in the right hands?', defeat: 'Not these hands, apparently.', after: 'I joined to cure bond sickness. When did it turn into a leaderboard?' }, grunt());
  T('grey2', 'Hollow Admin', 'Grey', 'grey', [['dynamech', 40], ['sludgor', 40], ['armadrill', 41]], { intro: '', defeat: 'Unacceptable margin of error.' }, admin());
  T('lark2', 'Hollow Admin', 'Lark', 'lark', [['nightwing', 40], ['waspear', 40], ['banditoon', 41]], { intro: '', defeat: 'NOT AGAIN! THIS IS HARASSMENT!' }, admin());
  T('crane1', 'Director', 'Vesper Crane', 'crane', [['dynamech', 41, { moves: ['flashcannon', 'thunderbolt', 'ironwall', 'voltdash'] }], ['chimelle', 41, { moves: ['playrough', 'reflect', 'staticwave', 'flashcannon'] }], ['masquerail', 42, { moves: ['shadowball', 'psychic', 'calmmind', 'hypnosis'] }], ['stormhound', 43, { item: 'lifegem', moves: ['thunderfang', 'crunch', 'surgetackle', 'voltdash'] }]],
    { intro: '', defeat: 'So your bond is real. Real enough to hurt me.' }, admin({ money: 150, ai: 4, music: 'crane_battle', resonate: true, env: 'hq', items: { hyperpotion: 2 } }));
  // --------------------------------------------------------- SKYREACH GYM
  T('sg_1', 'Dragon Tamer', 'Ryu', 'dragontamer', [['nimbling', 38], ['stratowyrm', 40]], { intro: 'Dragons answer only to the strong!', defeat: 'I am not strong enough... yet.', after: 'Ice and Fairy moves are a dragon\'s worst nightmare.' }, gymO());
  T('sg_2', 'Dragon Tamer', 'Mei', 'dragontamer', [['riptalon', 40]], { intro: 'My Riptalon was a Flopfin once. I NEVER gave up on it!', defeat: 'I\'ll never give up on it either.', after: '...' }, gymO());
  T('sg_3', 'Dragon Tamer', 'Oro', 'dragontamer', [['raptorix', 41], ['stratowyrm', 41]], { intro: 'Kaelen trained me personally! Prepare yourself!', defeat: 'Kaelen will be proud of you. Quietly. With one eyebrow.', after: 'Draco Meteor lowers Sp. Atk after use. Switch out!' }, gymO());
  T('kaelen', 'Warden', 'Kaelen', 'kaelen', [['riptalon', 43, { moves: ['crunch', 'cascade', 'wyrmdance', 'dragonrush'] }], ['stratowyrm', 43, { moves: ['dragonpulse', 'agility', 'wyrmdance', 'dragonclaw'] }], ['raptorix', 44, { moves: ['crunch', 'dragonclaw', 'rockslide', 'rocktomb'] }], ['tempestral', 45, { item: 'dragonfang', moves: ['dragonrush', 'airslash', 'wyrmdance', 'dragonclaw'] }]],
    { intro: '', defeat: 'The storm has passed. You are worthy of the dragons\' respect.' }, leader({ resonate: true, items: { hyperpotion: 2 }, env: 'sky' }));
  // --------------------------------------------------------------- ROUTE 6
  T('r6_sailor', 'Sailor', 'Hank', 'sailor', [['crustank', 40], ['riptalon', 40]], { intro: 'The Mere\'s been restless lately! So have I!', defeat: 'Calm seas now.', after: 'The lighthouse went dark last night. First time in my life. The whole sea felt it.' });
  T('r6_swim1', 'Swimmer', 'Marina', 'swimmer_f', [['jellume', 41], ['tidetail', 41]], { intro: 'Going to the Lodestar? Beat me first!', defeat: 'Go. Hurry.', after: '...' });
  T('r6_swim2', 'Swimmer', 'Finn', 'swimmer', [['lilyking', 41]], { intro: 'I swim this route every day! For training! And spite!', defeat: 'Tomorrow I swim twice.', after: '...' });
  T('r6_ace', 'Ace Tamer', 'Solen', 'ace', [['galeclaw', 42], ['crustank', 42], ['lumitail', 42]], { intro: 'I heard the Champion is watching you. Let me see why.', defeat: 'I see now.', after: 'Bond evolutions love a well-fed, well-walked team. Walk your Echoes.' }, { money: 55, ai: 3 });
  T('r6_grunt', 'Hollow Grunt', 'Grunt', 'grunt', [['banditoon', 42], ['nightwing', 42]], { intro: 'The Director\'s moment is at hand! None shall pass!', defeat: 'I... I passed out.', after: '...' }, grunt());
  // ---------------------------------------------------------- LIGHTHOUSE
  T('lh_grunt1', 'Hollow Grunt', 'Grunt', 'grunt', [['sludgor', 43], ['gnawmaw', 43]], { intro: 'The Engine is almost charged!', defeat: 'Charge... interrupted...', after: '...' }, grunt());
  T('lh_grunt2', 'Hollow Grunt', 'Grunt', 'grunt_f', [['nightwing', 43], ['dynamech', 44]], { intro: 'Can you hear it? The song is fading...', defeat: 'I don\'t want the song to fade...', after: 'Maybe we\'re on the wrong side. I think we\'ve been on the wrong side for a while.' }, grunt());
  T('lh_sci', 'Hollow Scientist', 'Dr. Pell', 'scientist', [['dynamech', 44], ['chimelle', 44]], { intro: 'We meet again! My readings predicted you!', defeat: 'My readings predicted this too. I hoped they were wrong.', after: '...' }, grunt());
  T('grey3', 'Hollow Admin', 'Grey', 'grey', [['dynamech', 45], ['sludgor', 46], ['armadrill', 46], ['craggolem', 46]], { intro: '', defeat: 'Calculations complete. We were wrong.' }, admin({ items: { hyperpotion: 1 } }));
  T('lark3', 'Hollow Admin', 'Lark', 'lark', [['nightwing', 45], ['waspear', 46], ['banditoon', 46], ['stormhound', 46]], { intro: '', defeat: '...Okay. Okay. Go. Stop her.' }, admin({ items: { hyperpotion: 1 } }));
  T('crane2', 'Director', 'Vesper Crane', 'crane', [['chimelle', 47, { moves: ['playrough', 'reflect', 'staticwave', 'flashcannon'] }], ['masquerail', 48, { moves: ['shadowball', 'psychic', 'calmmind', 'twistroom'] }], ['dynamech', 48, { moves: ['flashcannon', 'thunderbolt', 'ironwall', 'voltdash'] }], ['hootsage', 48, { moves: ['psychic', 'airslash', 'roost', 'calmmind'] }], ['stormhound', 50, { item: 'lifegem', moves: ['thunderfang', 'crunch', 'surgetackle', 'voltdash'] }]],
    { intro: '', defeat: 'Lumi... I\'m sorry.' }, admin({ money: 200, ai: 4, music: 'crane_battle', resonate: true, env: 'lighthouse', items: { hyperpotion: 2, fullrestore: 1 } }));
  // ---------------------------------------------------------- VICTORY ROAD
  T('vr_ace1', 'Ace Tamer', 'Vale', 'ace', [['stratowyrm', 46], ['cinderwing', 47], ['crustank', 47]], { intro: 'Only the best reach Victory Road. Are you one of them?', defeat: 'You are.', after: 'Keep your team healthy. There\'s no Haven down here. Only rocks. And regret.' }, { money: 60, ai: 3 });
  T('vr_ace2', 'Ace Tamer', 'Iris', 'ace_f', [['aurorelle', 47], ['luminelle', 47], ['hootsage', 48]], { intro: 'Beauty and power! Let\'s dance!', defeat: 'What a lovely battle. I lost beautifully.', after: '...' }, { money: 60, ai: 3 });
  T('vr_vet', 'Veteran', 'Bram', 'veteran', [['craggolem', 48], ['glaciursa', 48], ['slumbruin', 48]], { intro: 'I challenged the Conclave nine times. You get one battle with me.', defeat: 'Maybe you\'ll make it on your first try. That would be so annoying.', after: 'Seraphine sets up Calm Mind. Hit her hard and fast before she gets smug.' }, { money: 70, ai: 3 });
  T('vr_bb', 'Blackbelt', 'Kenji', 'blackbelt', [['grandmonk', 47], ['scarabrute', 48], ['thornhare', 48]], { intro: 'Rook of the Conclave is my master! HYAH!', defeat: 'Master Rook will be... disappointed. He\'ll say it\'s fine. It won\'t be fine.', after: 'Rook\'s team hates Flying and Psychic moves.' }, { money: 60, ai: 3 });
  T('vr_dt', 'Dragon Tamer', 'Zola', 'dragontamer', [['riptalon', 48], ['raptorix', 49]], { intro: 'Kaelen\'s rival, at your service!', defeat: 'Tell Kaelen I said hi. Grudgingly.', after: '...' }, { money: 60, ai: 3 });
  // ------------------------------------------------------------ CONCLAVE
  T('rook', 'Conclave', 'Rook', 'rook', [['scarabrute', 50, { item: 'sunberry' }], ['thornhare', 51, { item: 'lifegem' }], ['frostemper', 51, { item: 'blackbelt' }], ['grandmonk', 53, { item: 'leftovers', moves: ['closecombat', 'zenstrike', 'drainpunch', 'braceup'] }]],
    { intro: 'I am Rook, first wall of the Conclave. I\'ve broken stone with my fists and my heart with defeat. Neither made me quit. Show me your resolve!', defeat: 'A mighty will. Go on. The next wall is higher. And meaner.' }, elite({ items: { fullrestore: 1 } }));
  T('seraphine', 'Conclave', 'Seraphine', 'seraphine', [['chimelle', 51, { item: 'lumenberry' }], ['hootsage', 52, { item: 'sunberry' }], ['lumitail', 52, { item: 'twistedspoon' }], ['masquerail', 54, { item: 'leftovers', moves: ['psychic', 'shadowball', 'calmmind', 'twistroom'] }]],
    { intro: 'I\'ve already seen how this battle ends, little Tamer. But the future is only a guess until someone makes it true. Let\'s find out together.', defeat: 'How wonderful. I was wrong. I\'m never wrong. This is thrilling.' }, elite({ items: { fullrestore: 1 } }));
  T('nyx', 'Conclave', 'Nyx', 'nyx', [['banditoon', 52, { item: 'sunberry' }], ['nightwing', 53, { item: 'sharpbeak' }], ['umbratail', 53, { item: 'leftovers' }], ['stormhound', 54, { item: 'lifegem' }], ['phantomane', 55, { item: 'blackglasses', moves: ['darkpulse', 'shadowball', 'nightslash', 'wispflame'] }]],
    { intro: '...You want to know why I battle in the dark? Because it\'s honest. Nothing hides here. Not even you.', defeat: '...Heh. You shine too bright for the dark. Annoying.' }, elite({ items: { fullrestore: 1 } }));
  T('ferrum', 'Conclave', 'Ferrum', 'ferrum', [['coffret', 53, { item: 'spikedhelm' }], ['armadrill', 54, { item: 'leftovers' }], ['chimelle', 54, { item: 'sunberry' }], ['dynamech', 55, { item: 'magnet' }], ['tidalrus', 56, { item: 'metalcoat', moves: ['anchorslam', 'cascade', 'icicledrop', 'braceup'] }]],
    { intro: 'I forged my first Echo\'s armor from scrap when I was your age. Every dent is a story. Let\'s add one. Yours or mine.', defeat: 'A fine dent indeed. The Champion is waiting, young smith.' }, elite({ items: { fullrestore: 2 } }));
  // ------------------------------------------------------------ POST-GAME
  T('wanderer', 'Wanderer', '???', 'wanderer', [['riptalon', 72, { item: 'leftovers' }], ['slumbruin', 72, { item: 'sunberry' }], ['sylvantler', 73, { item: 'lifegem' }], ['tidalrus', 73, { item: 'leftovers' }], ['solarynx', 73, { item: 'focuslens' }], ['tempestral', 75, { item: 'lifegem' }]],
    { intro: '...', defeat: '......!' }, { money: 300, ai: 4, boss: true, resonate: true, music: 'wanderer', victory: 'victory_champion', noRematch: true, env: 'snow' });
})();
